environment = "testnet-3"

[connections]
server_addr = "0.0.0.0:21337"
known_peers = ["127.0.0.1:21337"]
outbound_limit = 1
bootstrap_peers_period_seconds = 1

[storage]
db_path = ".witnet-rust-testnet-6"

[jsonrpc]
enabled = true
server_address = "127.0.0.1:21338"

[consensus_constants]
checkpoints_period = 30
checkpoint_zero_timestamp = 1567036800
genesis_hash = "00000000000000000000000000000000000000007769746e65742d302e342e30"

[wallet]
testnet = true
node_url = "127.0.0.1:21338"
db_path = ".witnet-rust-testnet-6-wallet"

[log]
level = "error"